const header = document.querySelector('header');
const form = document.querySelector('form');
const p = document.querySelector('.d-none');
let currentID;
let currentData;
const gradeform = new GradeForm(form);
const pageheader = new PageHeader(header);
const gradetable = new GradeTable(table, p);
const app = new App(gradetable, pageheader, gradeform);
app.start();
