const header = document.getElementsByTagName('header')[0];
const form = document.getElementsByTagName('form')[0];
const p = document.getElementsByClassName('d-none')[0];
let currentID;
let currentData;
const gradeform = new GradeForm(form);
const pageheader = new PageHeader(header);
const gradetable = new GradeTable(table, p);
const app = new App(gradetable, pageheader, gradeform);
app.start();
